### ISSUE TITLE
"Or" operator: err.Tag() contain all tag  around "|"

### ISSUE THREAD

**Issue by MrSwed** [go-playground/validator#1033]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10: 
v10

### Issue, Question or Enhancement:

when I use [Or Operator ](https://pkg.go.dev/gopkg.in/go-playground/validator.v10#hdr-Or_Operator),   
 err.Tag() contain all tag  around  `|`

### Code sample, to showcase or reproduce:

```go
type someStruct struct {
//... 
	SortOrder   *int              `json:"sortOrder" db:"sort_order"  validate:"omitempty,gte=10|lte=-1"`
//...
}

 err := Validator.Struct(form)
// err.Tag() = "gte=10|lte=-1"
```
Expected only one tag, which trigger error

also err.Param() contain alwais last value regardless order of tag

**Comment by zemzale** [comment]
This is expected, since OR validation requires both tags to fail, which means both of them failed. 

You could play around by inverting the validation and using AND validation, which would report the tag for the first validation that failed, but with OR validation you will not get this kind of functionality.
