### ISSUE TITLE
Null, nil and zero value handling

### ISSUE THREAD

**Issue by dennisfaust** [go-playground/validator#198]
We have a situation with tokens as strings in our system where null is valid and filled is valid but blank is not. I'm using the https://github.com/guregu/null library and null.String as the field type. I've written a custom validator and have registered a Valuer for null.String{}. This setup works to pass along zero string values and filled in strings but nils are rejected as failing my validation before they get to either the valuer or the Validator. I'm wondering if you could give me your thoughts on how best to resolve this?

**Comment by joeybloggs** [comment]
would you be able to provide a code sample that includes your Valuer function and Struct/Field your validating?

I think it may be that your have required set as a validation, but exists is what your looking for...but I can't really tell without a sample.

**Comment by dennisfaust** [comment]
https://gist.github.com/dennisfaust/a91af314b1ad06567c90

**Comment by joeybloggs** [comment]
Thanks @dennisfaust I will take a look later tonight after I get off work, should be able to come up with something.

**Comment by joeybloggs** [comment]
#### Comments & Solution
OK @dennisfaust I must say this is definitely a unique case because the kind of null.StringFromPtr(nil) is invalid so you have a value that can be invalid, the default string value and an actual value; not many can be all three, but validator can handle it! :smile: and it's relatively simple just change your struct to the following

```go
type testNotBlankStruct struct {
	ID    string
	Token null.String `validate:"gt=0,omitempty,notblank"`
}
```

* omitempty handles the nil value and kind invalid
* gt=0 handles the blank value

#### Side note
You can probably eliminate the custom validator and have the "notblank" tag removed like so:
```go
type testNotBlankStruct struct {
	ID    string
	Token null.String `validate:"gt=0,omitempty"`
}
```
unless you are using the gorm parameter for something in your full code...

#### Final Thoughts
Please let me know if this solution works for you, I'll leave the issue open until then.

**Comment by joeybloggs** [comment]
Hey @dennisfaust just trying to confirm, did this worked for you?

**Comment by joeybloggs** [comment]
closing.

**Comment by dennisfaust** [comment]
From @joeybloggs: 

Comments & Solution

OK @dennisfaust I must say this is definitely a unique case because the kind of null.StringFromPtr(nil) is invalid so you have a value that can be invalid, the default string value and an actual value; not many can be all three, but validator can handle it! :smile: and it's relatively simple just change your struct to the following

type testNotBlankStruct struct {
    ID    string
    Token null.String `validate:"gt=0,omitempty,notblank"`
}
omitempty handles the nil value and kind invalid
gt=0 handles the blank value
Side note

You can probably eliminate the custom validator and have the "notblank" tag removed like so:

type testNotBlankStruct struct {
    ID    string
    Token null.String `validate:"gt=0,omitempty"`
}
