### ISSUE TITLE
Field name in custom validation function

### ISSUE THREAD

**Issue by irregular** [go-playground/validator#231]
Is there a way to find out the name of the field being validated?

```
func CustomValidator(v *validator.Validate, model reflect.Value, currentStructOrField reflect.Value, field reflect.Value, fieldType reflect.Type, fieldKind reflect.Kind, param string) bool {
     // HERE?		
}
```
I'm relatively new to Go, so sorry if this is a dumb question.

**Comment by joeybloggs** [comment]
hey @irregular,

I don't think there is the way validator works now; but maybe if you give me some more details and maybe an example of why you need it I could help you find a solution or maybe add support for that in the future if it makes sense.

**Comment by irregular** [comment]
I got an arbitrary amount of structs required validation using the very same services. I thought it might be possible using reflection.

I'd like to do something like this

```
type T1 struct {
    Name `validate:"uniqueness"`
}
type T2 struct {
    Tag `validate:"uniqueness"`
}

func UniquenessValidator(v *validator.Validate, topStruct reflect.Value, currentStructOrField reflect.Value, field reflect.Value, fieldType reflect.Type, fieldKind reflect.Kind, param, fieldName string) bool {
    topStructElem := topStruct.Elem()
    return IsUnique(fieldName, field, topStructElem)
}
```

I got a pull request ready if that makes sense.

Thanks

**Comment by joeybloggs** [comment]
Ok so just so I understand fully your looking to ensure that no struct has a field name exactly like the other?

**Comment by joeybloggs** [comment]
Sorry just trying to fully wrap my head around the what and why. Is there a particular reason for this requirement? Maybe just need a few more details. Before making a breaking change I like to have the big picture.

**Comment by irregular** [comment]
I'm trying to use this along with [gorm](https://github.com/jinzhu/gorm) as a way to prevent hitting the database for validation. In this case, I can't prevent such thing but I would like to keep validation in the same place. I don't want to let the DB handle validation, I need more control as I may need to store data somewhere else in the future(think a micro-service architecture)
Make sense?

**Comment by joeybloggs** [comment]
I understand now, I do a similar thing to ensure that a users email is unique in the database prior to saving.

Although a little more work instead of using a custom field validation, and the way I also do it,  I recommend using a struct level validation like in the examples here https://github.com/go-playground/validator/blob/v8/examples/struct-level/struct_level.go

The reason I do it that way is because not only do you usually need to ensure that field is unique but that when updating an existing record that if the database tables unique field is the same or not and trying to make that generic is a pain and you end up with a big switch statement that's not very flexible.

Would this approach work for you?

**Comment by irregular** [comment]
I think that would work for now.
Please consider adding field name as a parameter for the custom validator for future versions as it would help to do more complex and reusable functions

Thanks

**Comment by joeybloggs** [comment]
I don't disagree @irregular just as soon as I make that sort of change someone else will ask for the Custom field name I.e. json name.... And probably more params and I'm just worried that the Custom validator function will start to contain too many parameters..

I have been looking into passing a single object with all the params including field name just trying to work out how to keep allocations down and speed up because of all of the recursion.

If and when I get that working I will let you know and thanks for letting me know there was a need.
