### ISSUE TITLE
Failing test on master

### ISSUE THREAD

**Issue by kbalonek** [go-playground/validator#237]
Running in a Docker container from the official golang:1.6 image, I see 2 failing tests:

```
docker run -it --rm golang:1.6
$:/go# go get gopkg.in/go-playground/validator.v8
$:/go# go get gopkg.in/go-playground/assert.v1
$:/go# cd src/gopkg.in/go-playground/validator.v8/
$:/go/src/gopkg.in/go-playground/validator.v8# go test .
--- FAIL: TestUrl (0.00s)
	validator_test.go:4997: Index: 0 URL failed Error: Key: '' Error:Fiecd ld validation for '' failed on the 'url' tag
--- FAIL: TestUri (0.00s)
	validator_test.go:5061: Index: 0 URI failed Error: Key: '' Error:Field validation for '' failed on the 'uri' tag
FAIL
FAIL	gopkg.in/go-playground/validator.v8	0.009s
```

**Comment by joeybloggs** [comment]
Thanks I will look into this right away

**Comment by joeybloggs** [comment]
Tracked it down to this change in Go [617c93c](https://github.com/golang/go/commit/617c93ce740c3c3cc28cdd1a0d712be183d0b328#diff-6c2d018290e298803c0c9419d8739885L195)

code now get's into the **if** and reports an invalid character. The URL however is valid, just not according to [ParseRequestURI](https://golang.org/pkg/net/url/#ParseRequestURI) which assumes the request was sent via the browser and hence the fragment/suffix # will have already been removed.

can't use [Parse](https://golang.org/pkg/net/url/#Parse) because it's dumb in comparison, even lets "" pass :-1: 

so will keep as is and just emulate what the browser does and strip the # suffix prior to validation.

fix coming **forthwith**

**Comment by joeybloggs** [comment]
correction completed in release [v8.17.1](https://github.com/go-playground/validator/releases/tag/v8.17.1)

thanks for reporting @kbalonek
