### ISSUE TITLE
Characters in any language

### ISSUE THREAD

**Issue by byrnedo** [go-playground/validator#239]
Just wondering whether you'd consider adding a built in for charcters from any language.

Like: 
```
^[\p{L}]+$`
```
or for a name in any langage:
```
^\p{L}[\p{L}\s]*\p{L}$`
```
Edit: 
Does `ascii` or `printascii` maybe achieve this too?

**Comment by joeybloggs** [comment]
Hello @byrnedo 

absolutely I'd be interested, I could just update the "alphanum" regex found [here](https://github.com/go-playground/validator/blob/v8/regexes.go#L6) I don't know that Go's regex handles \p and {L} as I think they are PERL (PCRE) only, so I'd have to look into it. Any help you could provide is welcome 😄  I've gotten a bunch of requests lately for other projects, it may take me a little while to get to this, but I will.

As for a name in any language, this is allot more complicated, I'm not against it, just that I don't believe a single regex can be made to handle all situations i.e. regex to validate name "John A. Smith" would also say the name "Dr. John Smith" is valid, but "Dr." is a title not name.... It may just be better to validate names as "alphanum" or split up the fields into First + Last name instead of a single field/variable.

**Comment by byrnedo** [comment]
Hi @joeybloggs!

The `\p{L}` thing seems to work, I added it to a simple wrapper I have for your library here: https://github.com/byrnedo/svccommon/blob/master/validate/validate.go

The (extremely) simple tests seem to pass (https://github.com/byrnedo/svccommon/blob/master/validate/validate_test.go)

I agree with the name one, it's more up to each user to decide about.

I could add it at some point with a fork if you're busy, no problem, good to discuss it here first :)

**Comment by joeybloggs** [comment]
that is true that most would expect it to be [a-zA-Z0-9], however that is ascii only, I can't see any harm in allowing unicode, because if anyone needed a field to specifically contain ascii only they should also already be using the builtin ascii validator as well.

yes if you could fork and make a pull request, that would be extremely helpful. 👍  might be a good idea to update both of there regex's:
```
alphaRegexString          = "^[a-zA-Z]+$"
alphaNumericRegexString   = "^[a-zA-Z0-9]+$"
```

**Comment by joeybloggs** [comment]
Hey @byrnedo if you are still interested in this, I would definitely accept a pull request; but am closing for now.
