### ISSUE TITLE
Unexpected behavior with pointers

### ISSUE THREAD

**Issue by kujenga** [go-playground/validator#244]
Using v8 the following program prints out an error. I solved the issue by using the `omitempty` tag in conjunction with `max`, but I'm still confused as to why this was necessary. Is this a bug? I couldn't find much information in the docs about the treatment of pointers.

```go
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v8"
)

var validate = validator.New(&validator.Config{TagName: "v"})

func main() {

	type S struct {
		V *string `v:"max=10"`
	}

	s := new(S)

	fmt.Println(validate.Struct(s))
}
```
output:
```
$ go run test.go 
Key: 'S.V' Error:Field validation for 'V' failed on the 'max' tag
```

**Comment by joeybloggs** [comment]
Although maybe a bit confusing, this is the expected behaviour.

validator sees that there are validations that it is supposed to check, but has not been told it is ok to be nil and therefore fails on the `max` tag as it cannot be checked.

adding `omitempty` is the correct action if it is ok to be nil, otherwise because it's a pointer can use `exists` tag to ensure a value exists.

Side note: I know the `exists` tag and `required` tag are a bit confusing as required kind of implies exists; required should really be `nondefault` and I will correct this in v9 some day, but right now would break a great deal of existing code.

I hope this explanation makes sense?

**Comment by kujenga** [comment]
Gotcha, I was worried it might be looking at the actual value of the pointer or something of that nature, your explanation is much more sane. Thanks!

So is it true that if a pointer is non-nil then it is treated in the same way as a literal value of that type?

**Comment by joeybloggs** [comment]
Awesome :)

yes if a pointer is non nil, validator will extract the actual literal value and then validate agains't that. You can see how in the [ExtractType function](https://github.com/go-playground/validator/blob/v8/util.go#L38) which is called before checking any values.

**Comment by kujenga** [comment]
Perfect, that clears it up for me. Thanks so much!
