### ISSUE TITLE
Dive into and validate map keys?

### ISSUE THREAD

**Issue by adrian-sgn** [go-playground/validator#254]
### Package version eg. v8, v9:

v9
### Issue, Question or Enhancement:

Question
### Code sample, to showcase or reproduce:

``` go

package main

import (
    "fmt"
    "gopkg.in/go-playground/validator.v9"
)

type LangCode string
type Label map[LangCode]string

type TestMapStructPtr struct {
    Label Label `validate:"lang_code,dive,required"`
}

var validate *validator.Validate

func main() {

    validate = validator.New()
    validate.RegisterValidation("lang_code", ValidLangCode)

    label := Label {
        "en":"Good morning!",
        "pt":"Bom dia!",
        "es":"¡Buenos días!",
        "is":"Góðan daginn",
    }

    err := validate.Struct(TestMapStructPtr{label})
    // hoping to catch that "is" key is not valid
    if err != nil {
        fmt.Printf("label not valid! %s\n", err)
    }
}

func ValidLangCode(fl validator.FieldLevel) bool {
    validLangCodes := map[string]bool{
        "en":true,
        "es":true,
        "pt":true,
    }
    fmt.Printf("Validating %s\n", fl.Field())
    return validLangCodes[fl.Field().String()]
}
```

Hello, I am very new to the validator so I apologize if I've misinterpreted the use of dive and maps!  I'm also aware the above can be accomplished with Label as a struct, but I'm wondering if validator supports validating map keys using custom validations.

Is there a way to validate the keys of a map?

The above code example, I was expecting the validation rule `"lang_code,dive,required"` would validate each map key against the `lang_code` validation, and the value as required.  

However, running the above code I see that ValidLangCode is receiving the entire map, not each key.  Is there any way to dive into the keys?  Trying other combinations of dive, lang_code, and required didn't seem to work.

thanks!

**Comment by joeybloggs** [comment]
Hey @adrian-sgn , thanks for the question

The dive tag is really used to dive into the values of a map or array not the keys. Usually the maps key type protects it from bad input.

I think the way you have done it is correct all you have to do is cast the field as `Label` instead of `String()` and iterate over all keys.

apologies for the short example, answering from my phone
```go

var ok bool

for k, v := range FL.Field().(Label) { // may also want to validate the cast to a label succeeds before this
    if _, ok = ValidLangCodes[k]; !ok {
         return false
    }
}

return true
```

**Comment by adrian-sgn** [comment]
Hey @joeybloggs thanks for the lightning fast response! :zap: 

I appreciate your suggestion with ``ValidLangCode`` to support looping through the map keys

My only issue with it is that the error message back probably won't say which key(s) are failing validation

**Comment by joeybloggs** [comment]
You are correct @adrian-sgn the key won't be returned,

the only way you could do that is using `StructLevel` validation, but may not be whay you want.

**Comment by adrian-sgn** [comment]
@joeybloggs I rewrote the eample using ``StructLevel`` validation -- seems to work! thanks!

```go
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
)

type LangCode string
type Label map[LangCode]string

type TestStruct struct {
	Label Label `validate:"dive,required"`
}

var validate *validator.Validate
var validLangCodes = map[LangCode]bool{
	"en": true,
	"es": true,
	"pt": true,
}

func main() {

	validate = validator.New()

	validate.RegisterValidation("lang_code", ValidLangCode)
	validate.RegisterStructValidation(TestStructLevelValidation, TestStruct{})

	label := Label{
		"en": "Good morning!",
		"pt": "",
		"es": "¡Buenos días!",
		"xx": "Bad key",
	}

	err := validate.Struct(TestStruct{label})
	if err != nil {
		for _, err := range err.(validator.ValidationErrors) {
			if err.Field()[0:5]=="Label" {
				if err.StructField()=="mapkey" {
					fmt.Println(err.Field(), "has invalid", err.Tag(), "\"" + err.Param() + "\"")
				} else if err.Tag()=="required" {
					fmt.Println(err.Field(), "is required")
				}
			}
		}
	}
}

func ValidLangCode(fl validator.FieldLevel) bool {
	return validLangCodes[LangCode(fl.Field().String())]
}

func TestStructLevelValidation(sl validator.StructLevel) {
	st := sl.Current().Interface().(TestStruct)

	for k, _ := range st.Label {
		if !validLangCodes[k] {
			sl.ReportError(st.Label, "Label", "mapkey", "lang_code", string(k))
		}
	}
}
```

$.02 - perhaps a tag like ``dive`` but rather ``keys`` (or ``mapkeys``) could be introduced later on, eg. ``keys,lang_code,dive,required``

**Comment by joeybloggs** [comment]
Not a bad idea, I was thinking of how to do it and a `keys` tag would definitly work.

I will look at adding this in the weeks to come :)

**Comment by joeybloggs** [comment]
Hey @adrian-sgn I took a preliminary stab at this and is currently under the `validate-map-keys` branch if you wanted to check it out and let me know if it works for you; I did build your example directly into the test [here](https://github.com/go-playground/validator/blob/validate-map-keys/validator_test.go#L6540) so you can take a look and reverse engineer.

#### How it works
- add two new tags `keys` and `endkeys` ( needed to know when done with keys because of the multidimensional nature )
- example:
```go
// for a map of
map[string]string

// and validation tag's would be
`validate:"gt=0,keys,lang_code,endkeys,dive,required"`

// and the validation with check `lang_code` against all keys and then continue and validate required on the values
```

**Comment by adrian-sgn** [comment]
hi @joeybloggs - amazing work, I can't believe you turned that around so fast!

After studying a little more the code, I understand why you introduced `endkeys`. The examples you presented are pretty clear, and definitely show how to dive into map keys now. Nice work!

Drifting a little outside the original Issue, what seems to be missing now for map validation is the ability to validate ``key, value`` pairs together, and report errors to know which key/value had what error(s). 

I wonder about the possibility of a MapLevelValidation which could be similar to StructLevel in that you could add Errors for map keys, and also have the opportunity to validate the key and value together if needed.  If we had MapLevelValidation, how important would keys...endkeys be?

For example...

```go
// validator.registerMapValidation(tag string, fn MapLevelFunc)
validator.registerMapValidation("map_tag", MyMapFunc)

// ex. for a map of
map[string]string

// tags could be
`validate:"gt=0,map_tag,dive,required`
```

not sure what would happen if you used ``map_tag`` on a non-map type, though...

Thanks for being so attentive to this issue! 👍

**Comment by joeybloggs** [comment]
Hey @adrian-sgn not a bad idea, but this library is designed for tags to only apply to a single value instead of a type and that's why once you get into a certain level of complexity, it's usually better to use struct level validation, however you did give me a couple ideas I'll have to think about.

1. Instead of/complimentary to struct level validation have a custom type validation where you register a type to be validated, much like struct level but for any type.

2. Allow struct tags to not just point to a validation functions but custom type function, like number. 1 above but also have to provide a tag name.

Wow just got v9 out and these things although could be added in a backward compatible way, but will completely change the backend lol :smile: but this is exactly why I love open source with many people contributing ya can end up with something better than you could have imagined, just on your own 👍 

I'll hold off adding key diving until I explore the above 2 options.

**Comment by 23doors** [comment]
Any progress on that?

**Comment by joeybloggs** [comment]
Hi @23doors I had a working implementation, but was considering perhaps adding the Map validation function instead as checking map values it usually about checking a range of values, which would be better to do in a custom function rather than in Struct tags as a hard coded list.

Either way, map keys can already be checked by registering a StructLevel validation..Which is almost exactly like a map validation function; and works with the struct tags as well.

Maybe if you can give me an example of your use case I can better determine what the best course of action to take.

**Comment by 23doors** [comment]
@joeybloggs thanks, I'll just go with StructLevel validation for now. Looks like a pretty clean solution.

**Comment by joeybloggs** [comment]
Thanks @23doors and that's exactly why I haven't closed or completed this issue as nobody hasn't been able to satisfy their needs with struct level validation; so why add more complication to the library :)

But if someone can give me a use case for it, I'd definitely pursue it again.

**Comment by 23doors** [comment]
One downside to using custom structlevel or fieldlevel validation, it seems that you cannot use govalidator checks anymore. E.g. I would like to validate map[string]string that:
each key and value is printable ascii, key min/max length etc. Seems that I need to implement these checks by hand. Maybe consider exposing check functions like govalidator does?

**Comment by joeybloggs** [comment]
@23doors I don't expose the function directly but do through validate.Var(...)

So they are exposed but you can also apply multiple validation checks at a time and can use [ReportValidationErrors](https://github.com/go-playground/validator/blob/v9/struct_level.go#L57) from within struct level validation.

**Comment by 23doors** [comment]
@joeybloggs thanks! missed validate.Var(...) somehow

**Comment by joeybloggs** [comment]
@23doors I'd give a better example but am shopping and answering from phone...Let me know if you need any help.
