### ISSUE TITLE
Opposite of required: validate that the value is the default zero value

### ISSUE THREAD

**Issue by bokub** [go-playground/validator#299]
### Package version: 
v9

### Issue, Question or Enhancement:
How do I validate that the value **is** the data types default zero value ?
I'd like to ensure that a pointer is nil, or a string is equal to "". 

In short, is there a tag which is the opposite of `required`?

### Code sample, to showcase or reproduce:

```go
type order struct {
	ID       *string   `json:"id" validate:"forbidden"`
	Customer *Customer `json:"customer" validate:"forbidden"`
	SiteID   string    `json:"site_id" validate:"required,alphanum"`
}
```
I want to be sure that my user don't try to set 'ID' or 'Customer' in a specific request. How do I do that? (`forbidden` is not a real tag)

I have tried `"omitempty,lt=0"`, which works for ID but for Customer I also have to add tags inside the Customer struct, which is not ideal.

Thanks a lot

**Comment by joeybloggs** [comment]
@bokub sound like a pretty easy one to add, I'll add it as `isdefault` tag for clarity

**Comment by joeybloggs** [comment]
Hey @bokub 

I was well underway adding this new functionality, when I realized that this new tag would not play nice with other validations or program flow.

Your example illustrates it well, I can make `forbidden` error when a **Customer** is present that's fine, but then further in your program you're probably going to set a value for **Customer** and ID and want to validate that the values are correct and that's where the problems will start because now the `forbidden` is going to error, but we don't want it to.

It sounds like you're more interested in ensuring those values get set to their default values before proceeding rather than validating is that a fair statement?

If so I just finished a project that may be able to help https://github.com/go-playground/mold
I have not yet added a `default` tag and modifier function, but that was going to be my next project then you could ensure values are as you like prior to validating or working with them; what do you think?

**Comment by bokub** [comment]
Hi @joeybloggs

That is not my use case actually. 

I use the same struct for both the POST and PATCH requests, but I don't want some fields to be changed after they are set

To do that, I use two different custom tags so the validation rules are different, but the structure stays the same. 

When performing my database update, I tell mongo not to update nil or empty values,  so I want to ensure that some fields are actually set to their default.

**Comment by joeybloggs** [comment]
ok @bokub I'll continue this then.

**Comment by bokub** [comment]
Thanks @joeybloggs :+1:

**Comment by bokub** [comment]
Just replaced all my `omitempty,lt=0` with `isdefault`, that's a lot easier to read and understand

I can also write things such as 
```go
Customer *Customer `validate:"isdefault"`
```
and be sure Customer is a nil pointer

Thanks for your work :+1:

**Comment by joeybloggs** [comment]
No problem, glad I could make it work :)
