### ISSUE TITLE
translate field name

### ISSUE THREAD

**Issue by bsbak** [go-playground/validator#327]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:

How translate field name? 

### Code sample, to showcase or reproduce:

the result of errs.Translate(trans) is:
```User.Password:Password это обязательное поле // Password is required field```
but i need:
```User.Password:Пароль это обязательное поле```

i was create package
```
// github.com/bsbak/currentProject/global/translate
package translate

import (
	"strings"
)

type fieldTranslator map[string]map[string]string

var FieldTranslator fieldTranslator

func init() {
	FieldTranslator = New()
	FieldTranslator.Add("ru", "User.Password", "Пароль")
	FieldTranslator.Add("en", "User.Password", "Password")
}

func (ft fieldTranslator) Add(lang, field, name string) {
	_, ok := ft[lang]
	if !ok {
		ft[lang] = map[string]string{field: name}
		return
	}
	ft[lang][field] = name
}

func (ft fieldTranslator) Translate(ut ut.Translator, fe validator.FieldError) string {
	f, ok := ft[ut.Locale()][fe.StructNamespace()]
	if !ok {
		return fe.Field()
	}
	return  f
}

func New() fieldTranslator {
	return  make(fieldTranslator)
}
```
then i was modify "gopkg.in\go-playground\validator.v9\translations\en\en.go" and "gopkg.in\go-playground\validator.v9\translations\ru\ru.go"
```
//the lines like 
t, err := ut.T(fe.Tag(), fe.Field())
// to
t, err := ut.T(fe.Tag(), translate.FieldTranslator.Translate(ut, fe))
```
maybe here any default or better way?
```go

```

**Comment by joeybloggs** [comment]
Hey @bsbak thanks for the question,

what you’ve done is almost what is needed, the only changes I’d make are you don’t have to create your own field translator, but rather just add translations for the field names to the ut which the translate function already has access to; that way you don’t have to hack anything. You will have to `
RegisterTranslation` for each English translation just as you have for your Russian (looks like Russian).

I wish there was an easier way but the field name is a dynamic value. I have been thinking of how to improve ever since adding translations; I think in the next version I will allow registering of a translation function against a tag which only accepts context and the field error to allow people to use whatever they want to translate and even allow per request contextual information to be accessible.

P.S. sorry for no examples, not at a computer and answering from my phone.

Please let me know if you have any questions :)
