### ISSUE TITLE
Multiple RegisterStructValidation on a sing struct

### ISSUE THREAD

**Issue by alexdor** [go-playground/validator#333]
### Issue, Question or Enhancement: Question

I have registered 2 struct validations for the same struct, but only the 2nd one runs. Is there a way to have multiple custom validations for the same struct? 

### Code sample, to showcase or reproduce:

```go
        validate = validator.New()
	validate.RegisterStructValidation(stores.EmailRecipient.Validate, request.To)
	validate.RegisterStructValidation(stores.Email.Validate, request.Email)
```

**Comment by joeybloggs** [comment]
Hey @alexdor 

No currently there is no way to have multiple struct validations, internally only a reference to the struct's type is held, and why when registering 2 only the second is used as it overwrites/remaps the first. The reason that type is used is it's the only truly unique identifier between structs.

There are however there are some options, you could:
- Use [RegisterStructValidationCtx](https://godoc.org/gopkg.in/go-playground/validator.v9#Validate.RegisterStructValidationCtx) and pass in a value in the `Context` to indicate which validation to run inside a separate struct validation.
- Separate your structs, `To` and `Email`; in my experience have one structure represent multiple things will always eventually get you into trouble (only mentioning because you want to run different validations depending on struct usage)

**Comment by alexdor** [comment]
Hey @joeybloggs thanks for the response. Would you accept a pr that adds this feature?

**Comment by joeybloggs** [comment]
@alexdor I would definitely consider a PR, it all depends on how it would work, performance considerations and if there were any breaking changes.

**Comment by kke** [comment]
Also ran into this, but I'd like to add multiple different custom validations as separate functions to keep them short and sweet. Now I need to combine them into a single messy big one.

**Comment by peterzernia** [comment]
I have a generic struct ctx validator that works on many of my structs, and now a specific validator that works in addition to the generic one. It would be nice to be able to do

```go
validate = validator.New()
validate.RegisterStructValidationCtx(GenericValidator, EntityOne, EntityTwo, EntityThree)
validate.RegisterStructValidationCtx(SpecificEntityTwoValidator, EntityTwo)
```

instead in the GenericValidator, I have to do 
```go
validate.RegisterStructValidationCtx(GenericValidator, EntityOne, EntityTwo, EntityThree)

func GenericValidator(ctx context.Context, sl validator.StructLevel) {
        ...
	entity := sl.Current().Interface()
        v := reflect.ValueOf(entity)
	t := v.Type()

      // Call the additional validator for EntityTwo
       if t.Name() == 'EntityTwo' {
           SpecificEntityTwoValidator(ctx, sl)
       }

```
