### ISSUE TITLE
Enum value 0 will not pass validation in validate.Struct()

### ISSUE THREAD

**Issue by golden0080** [go-playground/validator#389]
### Package version eg. v8, v9: 
I tried this on v9. The same code doesn't seem to work with v8 import.

### Issue, Question or Enhancement:
When validating any golang struct with enum fields, and having a value of 0 for enum, the validation will not pass.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"

	"gopkg.in/go-playground/validator.v9"
)

type UserType int

const (
	USER_NORMAL UserType = iota // 0
	USER_ADMIN
)

// User contains user information
type User struct {
	UserType UserType `json:"type" validate:"required"`
	UserName string   `json:"name" validate:"required"`
}

// use a single instance of Validate, it caches struct info
var validate *validator.Validate

func main() {

	validate = validator.New()

	user := &User{
		UserName: "testUser",
		UserType: USER_NORMAL,
	}

	err := validate.Struct(user)
	if err != nil {

		fmt.Println("Validation failed.")
		fmt.Println()
		for idx, err := range err.(validator.ValidationErrors) {

			fmt.Println("err", idx)
			fmt.Println(err.Namespace())
			fmt.Println(err.Field())
			fmt.Println(err.StructNamespace()) // can differ when a custom TagNameFunc is registered or
			fmt.Println(err.StructField())     // by passing alt name to ReportError like below
			fmt.Println(err.Tag())
			fmt.Println(err.ActualTag())
			fmt.Println(err.Kind())
			fmt.Println(err.Type())
			fmt.Println(err.Value())
			fmt.Println(err.Param())
			fmt.Println()
		}

		return
	}
}

```

**Comment by joeybloggs** [comment]
Hey @golden0080 

This one's actually been asked  a bunch of times in different ways, it comes down to the way Go handles default values.

Think of the `required` tag as ensuring that the data is not set as the default value for the datatype, because Go always assigns a default value, in your case for the enum is **0**; there's no way to differentiate between a default value and an assigned values equal to a default value.

There are option however:
1. you could use `UserType` as a pointer eg. `UserType *UserType`, that way the default value is nil and so 0 will pass.

2. Don't use `required` and use another validation such as `gte=0`

3. Create a [custom validation](https://github.com/go-playground/validator/blob/v9/_examples/custom-validation/main.go) that handles the zero case for your enum specifically.

4. Register a [CustomTypeFunc](https://github.com/go-playground/validator/blob/v9/_examples/custom/main.go) for your enum type that will evaluate and return a different value that will pass or fail based on that returned value.

Which one you choose is really up to you and what's best for your use case; please let me know if this helps :)
