### ISSUE TITLE
Is it possible to slim down validator of locales and universal-translator?

### ISSUE THREAD

**Issue by gitste** [go-playground/validator#394]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

Hi, I am looking for a lightweight solution to validate structs and I do not need translation, validator depends on `locales` and `universal-translator` which are too big for my project. Is there an option to use validator without them?

**Comment by joeybloggs** [comment]
Hey @gitste 

sorry for the late reply, been super busy, I plan to leave it out as a hard dependency in the next version., but for now will have to stay.

I'm not sure what you mean by too big for your program, the translations are optionally registered and the reference to the locales and universal-translator package should only be minimally compiled in, not the entirety of it.

**Comment by gitste** [comment]
Hi @joeybloggs

Thanks for response, I am building a chaincode in golang for Hyperledger Fabric which will be loaded dynamically over the network, that is why I need it to be as small as possible. 

When I tried to compile my program with Validator I got an exception that I need Universal Translator which came with locales totally being ~60mb. The validator itself is ~3mb.

My usecase requires rather simple vadiations for structs which chaincode receives as parameters. eg. `required`, `dive`, `omitempty` and some custom tags with simple logic. 

Can you guide me how to trim validator?

Thanks

**Comment by joeybloggs** [comment]
So it depends on how you're pulling dependencies of the packages via `git clone` or `go get` go get iirc will pull all dips from sub-packages as well.

Regardless the fix is to change the `ut.Translator` references to an Interface to decouple it and that should get you what you want without breaking changes to the lib; I was planning to do this in v10 but wanted to also make a lot of other changes also at the same time.

I would like to make the changes, but not sure when I'll be able to get to them as I'm quite busy lately, but would definitly accept a PR f you need it sooner :)

does that make sense? if need be I can make an exception to make a premature v10, but would like to avoid that if at all possible, major updates can be very disruptive.

**Comment by gitste** [comment]
@joeybloggs 

I have taken asaskevich/govalidator, removed unnecessary files and it fulfils my needs without changes in the code. Thanks for help and good will.
