### ISSUE TITLE
Can error unified processing?

### ISSUE THREAD

**Issue by sun-wenming** [go-playground/validator#422]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Enhancement:
Can I concentrate the errors and handle them in a unified way?

### Code sample, to showcase or reproduce:

Like [beego/validation](https://beego.me/docs/mvc/controller/validation.md)
```go
name := c.PostForm("name")
	desc := c.PostForm("desc")
	content := c.PostForm("content")
	createdBy := com.StrTo(c.PostForm("created_by")).MustInt()
	state := com.StrTo(c.DefaultPostForm("state", "0")).MustInt()

	valid := validation.Validation{}
	valid.Required(name, "name").Message("标题不能为空")
	valid.Required(content, "content").Message("内容不能为空")
	valid.Required(createdBy, "created_by").Message((e.NOT_EMPTY_created_by))
	valid.Range(state, 0, 1, "state").Message("状态只允许0或1")

	if valid.HasErrors() {
		app.MarkValidErrors(valid.Errors)
		appG.ResponseFailMsg(valid.Errors[0].Message)
		return
	}
```

But now, my code is ：
```go
	id := com.StrTo(c.Param("id")).MustInt()
	if err := validate.Var(id, "gt=0"); err != nil {
		// app.MarkValidErrors(err.(*validator.ValidationErrors))
		appG.ResponseFailMsg(err.Error())
		return
	}
	state := -1
	if arg := c.PostForm("state"); arg != "" {
		state = com.StrTo(arg).MustInt()
		if err := validate.Var(state, "oneof=0 1"); err != nil {
			// app.MarkValidErrors(err.(*validator.ValidationErrors))
			appG.ResponseFailMsg(err.Error())
			return
		}
	}
...
```
Is there any good solution? Thanks.

**Comment by IsSwm** [comment]
Hey， @jadhub 
First it is `valid.Errors`.  
 `app.MarkValidErrors(...)`It's my encapsulated log record.Sorry.
```go
// A Validation context manages data validation and error messages.
type Validation struct {
	Errors    []*Error
	ErrorsMap map[string][]*Error
}
```
And I started to be at `validate.Struct(...)`.Like this.
```go
type DocEditTopic struct {
	// Name topic name
	Name string `json:"name" example:"主题名称" validate:"required"`
	// ModifiedBy modified id
	ModifiedBy int `json:"modified_by" example:"1" validate:"required"`
	// 0 can use, 1 not 
	State int `json:"state" example:"0" validate:"oneof=0 1" format:"(0~1)""`
}
```
`DocEditTopic.State` field is optional.But In struct initialization state default 0.(because int type) 
Like this ` map[name:主题名称 modified_by:1 state:0]`
I am not submit in http request body 
```
{
  "modified_by": 1,
  "name": "主题名称"
}
```

Caused me to have to separate state field from the structure. Separate verification state field.
So i want like `app.MarkValidErrors(...)` method unified processing of error messages.

But now.
I should not use the optional parameter defaults (with 0). So I can use the struct.And don't need  `app.MarkValidErrors(...)` method.
change code ignore 0
```go
State int `json:"state" example:"1" validate:"oneof=0 1 2" format:"(1~2)"`

if t.State != 0 {
     data["state"] = t.State
}
```

I will continue use `validate.Struct(...)`
Do you have any suggestions for default values of struct?
Thanks.

**Comment by jadhub** [comment]
Wrong Mention i guess. You probably wanted @joeybloggs.
