### ISSUE TITLE
Vary validation of struct when used in different contexts

### ISSUE THREAD

**Issue by mkadin** [go-playground/validator#434]
First off, thanks a ton for this package!  Much better than the validation stuff we rolled on our own at the start of our project.

### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

I'm wondering if there's a way to deal with an issue I've run into recently.  Let's say we have a custom type, which is intended to be used as a fairly low-level type.  It's used as a field in multiple other structs.  

For instance, let's say I run a movie-related website:
```
type Person struct {
    FirstName string
    LastName string
}

type User struct {
    Email string `validate:"required,email"`
    Author Person
}

type Movie struct {
    Title string  `validate:"required"`
    Director Person
}
```

Let's say our business logic demands that the `LastName` field is required for a movie's director but the `FirstName` is optional.  On Users, the `FirstName` is required but the `LastName` is optional.  Is there any way to vary the validation configuration across the various uses of the lower-level struct?

We could write custom validators for Person and do something like:
```
type User struct {
    Email string `validate:"required,email"`
    Author Person `validate:"required,firstNameRequired"`
}

type Movie struct {
    Title string  `validate:"required"`
    Director Person `validate:"required,lastNameRequired"`
}
``` 

But since the `FirstName` and `LastName` fields are just strings, we'd have to re-implement all sorts of base logic that this package comes with (e.g. gte, lt, email, uuid, etc).

Any ideas on how we can vary the validation on a struct depending on where it's used?

This is coming up for us using techniques like [this](https://www.calhoun.io/how-to-determine-if-a-json-key-has-been-set-to-null-or-not-provided/) or [this](https://gist.github.com/alexmcroberts/219127816e7a16c7bd70) where JSON behavior is having us use structs not fields for pretty low-level types across multiple structs.

**Comment by mkadin** [comment]
Seems like maybe from #245 that I can't actually do the custom validator solution I mentioned above, as those validations can only be written for fields which aren't a next level of struct, is that right?

**Comment by joeybloggs** [comment]
Hey @mkadin so there are a few options, only 2 you really want though:
1. Write a `struct level` validation where you can do the check to see if it's a director or normal person and validate from there.
2. Write custom validations as you eluded to above, since validation function accept `FieldLevel` interface which has access to the direct and top level parent structs https://github.com/go-playground/validator/blob/v9/field_level.go#L10 you should also be able to check if it's a director or person.

The approach is up to you and depends on how you want to maintain the validations going forward, one struct level with multiple cases or multiple validations handling less.

please let me know if that helps.

**Comment by joeybloggs** [comment]
thanks @mkadin been thinking about #245 a lot and hoping I can think of a way to combine both i nthe future.
