### ISSUE TITLE
Nil FieldError.Value() Behaviour

### ISSUE THREAD

**Issue by axopadyani** [go-playground/validator#439]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
I have a struct with string pointer that has `required` tag. If I validate that struct with nil value in it, that will return `FieldError` with `Value()` method that returns nil. But, if i do `err.Value() == nil` will return false.

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"
	"gopkg.in/go-playground/validator.v9"
)

type MyStruct struct {
	SomeString *string `validate:"required"`
}

func main() {
	myStruct := MyStruct{}

	validate := validator.New()
	err := validate.Struct(myStruct)
	if err != nil {
		valErr := err.(validator.ValidationErrors)[0]
		fmt.Println(valErr.Value(), valErr.Value() == nil)
                // prints <nil> false
	}
}

```

**Comment by joeybloggs** [comment]
Hey @axopadyani this is because to handle any type the [Value()](https://github.com/go-playground/validator/blob/v9/errors.go#L136) function needs to return type `interface{}` and so the value returned is actually an interface{} which points to the nil value and so not nil itself because of the extra indirection.

if you tried casting to the underlying type before checking equality you can detect nil eg. `valErr.Value().(*string) == nil`

**Comment by axopadyani** [comment]
Ah, I  see. All that makes sense now. Thanks for your help.
