### ISSUE TITLE
Field dependencies

### ISSUE THREAD

**Issue by KlausBuchegger** [go-playground/validator#445]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Hi, I just started looking into this package and I have a question:

Is it possible to add dependencies across multiple tags? Something like "one of these fields must not be empty" and "if C1 is non-empty, C2 has to bee non-empty too"

I have a struct that looks similar to the example below. I also listed three valid possibilities.
So either A is not empty (and B,C1,C2 are empty)
or B is not empty (and A,C1,C2 are empty)
or both C1 and C2 are not empty (and A,B are empty).

Are there already some tags built into the package that support dependencies like this? Or would I have to come up with a custom validator for this?

Also, is it somehow possible to combine the , and | operators to achieve some more complex logic in the tags?

### Code sample, to showcase or reproduce:

```go
type MyStruct struct {
  A string
  B string
  C1 string
  C2 string
}

var valid1 = MyStruct{
  A:"foo",
  B: "",
  C1: "",
  C2: "",
}
var valid1 = MyStruct{
  A:"",
  B: "bar",
  C1: "",
  C2: "",
}
var valid1 = MyStruct{
  A:"",
  B: "",
  C1: "some",
  C2: "stuff",
}
```

**Comment by joeybloggs** [comment]
Hey @KlausBuchegger 

to achieve that you'd have to create your own custom validator or struct validation. There are some validations for cross-field comparison, but nothing that will do conditional.

If you could come up with a generic one I'd gladly accept a PR :)

I had thought about adding more complex syntax support, however, I've found that if you need such complex logic you should be programming it in the language rather than the struct tags as it can become unreadable and combersome.

**Comment by KlausBuchegger** [comment]
Hey @joeybloggs 

Thanks for the reply, I created a struct validation function for this case. 
I thought about a tag like `choice=groupname` that checks all fields for this groupname tag and verifies that exactly one is non-empty. But this seemed rather inefficient, as it will be executed for every field with this tag.

I'm closing this issue with the result that it's not part of the current implementation.
