### ISSUE TITLE
Is validator reusable and sharable?

### ISSUE THREAD

**Issue by totemcaf** [go-playground/validator#479]
### Package version eg. v8, v9: 
v9

### Issue, Question or Enhancement:
Question

### Code sample, to showcase or reproduce:

Is the validator implementation reusable or should I create a new validator each time I need to validate a new value?

```
   validationError1 := validator.New().Struct(value1)
   validationError2 := validator.New().Struct(value2)
``` 
or it can be:
```
   myValidator := validator.New()
  validationError1 := myValidator.Struct(value1)
  validationError2 := myValidator.Struct(value2)
```

Can the validator instance be shared between two or more gorutines?

**Comment by deankarn** [comment]
The validator instance should only be created once and reused. After initializationg E.g. custom aliases or functions registered it is thread safe to use across goroutines.

For more context it uses a minimal internal cache for the struct information and validation mappings because reflection is expensive; recreating each time will make it far less efficient.
