### ISSUE TITLE
Is any possibility to use the validation function defined in validator?

### ISSUE THREAD

**Issue by cncal** [go-playground/validator#492]
### Package version: 

V9

### Issue, Question or Enhancement:

I'm working on my custom validation which may use some functions just like `isEq`, `hasValue` defined in `validator.v9` package. I have to copy those functions to my project for now. So is any possibility to reuse them out of package?

**Comment by deankarn** [comment]
@cncal I could definitely see this being useful when creating custom validations my motivation to not expose these originally was two-fold:
1. not clutter the library interface.
2. some validations can be remapped eg. overridden by registering a custom validation and by having these exposed the callers would not call the remapped version.

There is the option to already use these validations inside custom validation, however, using `validate.Var(...)`

You can call validations on specific fields from within the custom validation just as you can from outside, and also has the added benefit of honouring remapped validations.

Let me know if this helps.

**Comment by cncal** [comment]
LGTM. @deankarn thanks and feel free to close this issue.

**Comment by nmfzone** [comment]
Hey, sorry for commenting in old issue @deankarn. I need to call `hasValue` in my custom validation, how to do that? I've tried to copy the code to my app, but it seems the `fldIsPointer` in `hasValue` is private. Is there any other way?

**Comment by mbarnes** [comment]
Probably too late for @nmfzone but for anyone else...
I believe `fldIsPointer` is equivalent to the "nullable" return value from `FieldValue.ExtractType`.

> There is the option to already use these validations inside custom validation, however, using validate.Var(...)

I'm dissuaded from this alternative for a few reasons:

- The warning about unforeseen validations that appears in the docs:
  WARNING: a struct can be passed for validation eg. time.Time is a struct or if you have a custom type and have registered a custom type handler, so must allow it; however unforeseen validations will occur if trying to validate a struct that is meant to be passed to 'validate.Struct'
- It requires access to the `validate` instance.
- It takes an `interface{}` argument instead of a `reflect.Value`.

Seems like a new `FieldLevel` method for calling other validations on `fl.Field()`, similar to `validate.Var`, would be the best way to address this.
