### ISSUE TITLE
Ignore a particular tag for a field

### ISSUE THREAD

**Issue by Alireza-Ta** [go-playground/validator#501]
### Package version eg. v8, v9: 
v8

### Issue, Question or Enhancement:
Suppose this scenario We need `eqfield:ConfirmPassword` for registering purposes but in circumstances like login We do not need to specify `ConfirmPassword` and We only rely on the `Password` field.
Hence is there a way to neglect tags like `eqfield` in such conditions? Because otherwise, We'll get the error about `eqfield` did not get satisfied! 

### Code sample, to showcase or reproduce:

```go

```

**Comment by alinnert** [comment]
Normally you create a separate struct for every handler. The login route should use a struct that only contains `username` and `password`. In order to make this a simple thing, you can create a function for every handler that returns just that handler.

Example from the router site:

```go
r.Get("/auth/login", handleLogin())
```

The implementation of this function now can look like this:

```go
func handleLogin() http.HandleFunc {
  type requestData struct {
    username string `json:"username" validate:"required"`
    password string `json:"password" validate:"required"`
  }

  return func(w http.ResponseWriter, r *http.Request) {
    data := &requestData{}
    json.NewDecoder(r.Body).Decode(data)
  }
}
```

You can do this for every handler. Since the struct definition only lives inside this function you don't need to worry about name clashes, even if they're in the same package.

I think that's a better idea than making validation more complex.

**Comment by jmvbxx** [comment]
@Alireza-Ta Thanks for your question. It looks like this issue has been resolved. Please let us know if you have any follow-up questions. For now we're going to go ahead and close this issue.
