### ISSUE TITLE
How do I say required but could be default?

### ISSUE THREAD

**Issue by aneeskA** [go-playground/validator#504]
### Package version eg. v8, v9: 

v9

### Issue, Question or Enhancement:

How do I write a rule that says the key is required but the value could be default? For a string, empty is fine but null is not. How do I do that? I couldn't figure that out from docs and no helpful examples available also.

### Code sample, to showcase or reproduce:

```go

```

**Comment by deankarn** [comment]
@aneeskA an example would really help here, I'll attempt to answer based on my understanding of the question though:

There are a number of issues around this that I've left open, the TL;DR of it is you can use a `*string` instead of a `string` which can capture all the states you need to deal with eg. `nil`, `blank/empty` and another validation and then can use something like:
`omitempty,eq=""|othervalidation`

let me know if this helps

**Comment by jmvbxx** [comment]
@aneeskA Thank you for your question. It appears as if your concern has been addressed. Please let us know if you have any follow-up questions.
