### ISSUE TITLE
How is required_with and omitempty supposed to work when using custom type?

### ISSUE THREAD

**Issue by talmr** [go-playground/validator#540]
I am using validator v9, and I am not sure that I fully understand how I am supposed to use `required_with` and `omitempty`

I am using https://github.com/guregu/null and I am trying to validate those types by registering them.

However, I am wondering why the following example fails when I provide one of the `required_with` values, but not the other:

https://play.golang.org/p/VOnaac7l0HT

If I remove the `omitempty` on both fields that have it, then if I don't provide either, the struct validation just fails:

https://play.golang.org/p/kZngZuDDSxW

How can I use these tags correctly so that:

1.  if I pass in an ID and a Latitude, then it will fail.

2. if I pass in only an ID, then it should pass.

**Comment by deankarn** [comment]
Actually `omitempty` isn't required in this case. https://play.golang.org/p/jrmvMy9IQaC
```go
package main

import (
	"fmt"
	"reflect"

	"gopkg.in/go-playground/validator.v9"
	"gopkg.in/guregu/null.v3"
)

type Test struct {
	ID        int64      `validate:"required,numeric"`
	Latitude  null.Float `validate:"required_with=Longitude"`
	Longitude null.Float `validate:"required_with=Latitude"`
}

func main() {
	validate := validator.New()
	validate.RegisterCustomTypeFunc(nullFloatValidator, null.Float{})
	b := &Test{
		ID: 1,
		//Latitude: null.FloatFrom(34),
	}

	err := validate.Struct(b)
	fmt.Println(err)
}

func nullFloatValidator(field reflect.Value) interface{} {
	if valuer, ok := field.Interface().(null.Float); ok {
		if valuer.Valid {
			return valuer.Float64
		}
	}
	var f *float64
	return f
}
```

remember that `required` is really just checking if the value is it's default value, since you were returning `nil` from you're customer function, that would be the default/invalid value and it will appears `set`. By setting it to a `*float64` the default underlying type is nil/ptr and so be seen as `unset` by `required`.

This could be solved by returning other values but this seems the most appropriate.

Let me know if this helps @talmr, oh and PS. I released some fixes today, I recommend updating also.

**Comment by talmr** [comment]
@deankarn I really appreciate your explanation and example.  That is exactly what I was hoping to accomplish.  I will also upgrade to the latest version.

This library is amazing and has saved me a lot of time for struct validations!  Thank you very much!  🙏

**Comment by talmr** [comment]
@deankarn I actually do have one more question if that is okay.

When I register multiple of `.RegisterCustomTypes()`, I get a `Bad Field Type *Float64` panic.

Here is what I am doing:

```
        validate := validator.New()
	validate.RegisterCustomTypeFunc(nullStringValidator, null.String{})
	validate.RegisterCustomTypeFunc(nullIntValidator, null.Int{})
	validate.RegisterCustomTypeFunc(nullFloatValidator, null.Float{})
```
