### ISSUE TITLE
Expose Baked In Validators

### ISSUE THREAD

**Issue by jamesgoodhouse** [go-playground/validator#554]
Upon digging through the Git blame log I see that the baked in validators were previously exposed (https://github.com/go-playground/validator/commit/fc5d9f3ae0f19ada9361b84562db92d659c925ab) but less than a year later they were all made internal-only less than a year later (https://github.com/go-playground/validator/commit/e0e1af6a61dbd0608ffcdfd0fdae012b31d4229c). I'm curious as to the reasoning for this? I'm writing a custom validator currently, and would really like to leverage some of them so I don't have to rewrite the same code in my validator. I dug around in the code to see if there was some other mechanism to gain access to the internal validators, but nothing jumped out at me. Thanks for your time and awesome package!!

**Comment by deankarn** [comment]
Hey @jamesgoodhouse, the main reason was that having them exposed was just like having a leaky abstraction. 

I could not change them in any way without making a major version change as it could cause unexpected behavioural changes depending on how they were being used. Also, I was unable to do that same in changing their signatures for the same reasons.

Since most validations can simply be combined as they are run in sequence or by using the or operation `|` and so most people did not miss them being exposed.

The thing is that validations can also be used within other functions with the same tags by using `validate.Var(..., "tag1,tag2")` while maintaining the abstractions, albeit a little less efficient.

**Comment by jamesgoodhouse** [comment]
That makes complete sense to me. Thank you!
