### ISSUE TITLE
errors.is not working, when validator return error use errors.Is(err, validator.ValidationErrors{}) check return false

### ISSUE THREAD

**Issue by ganluo960214** [go-playground/validator#594]
### Package version eg. v8, v9: 
v10

### Issue, Question or Enhancement:

errors.is not working, when validator return error use errors.Is(err, validator.ValidationErrors{}) check return false

### Code sample, to showcase or reproduce:

```go
package main

import (
	"errors"
	"log"
	"reflect"

	"github.com/go-playground/validator/v10"
)

var (
	validate = validator.New()
	A        = 0
)

func main() {
	err := validate.Var(A, "eq=1")
	log.Println(err)
	log.Println(err == nil)
	log.Println(reflect.TypeOf(err))
	log.Println(errors.Is(err, validator.ValidationErrors{}))
}
```

https://play.golang.org/p/i8Dep_t347T

**Comment by deankarn** [comment]
@ganluo960214 yes that's true. This is also true of almost any non static errors in Go.

`ValidationErrors ` is really `type ValidationErrors []FieldError`

And so your checking of the error returned is equal to `validator.ValidationErrors{}` which is really `[] FieldError` which is `nil`.

So `errors.Is` is correct, it does not match.

You'll have to do one of the following, which I recommend doing more often in the first place:
```go
_, isType := err.(validator.ValidationErrors)
fmt.Println(isType)
```

```go
switch t := err.(type) {
    case validator.ValidationErrors:
        fmt.Println(t)
}
```

Side rant, I still think adding adding this new error logic to the STD lib was a mistake, and exactly for reasons like this!

**Comment by ganluo960214** [comment]
thanks. close it when it should.

**Comment by hampgoodwin** [comment]
Something very bizarre about this is that while `errors.Is` returns false, `errors.As` which also returns a bool returns true as we'd expect.

Would it be possible to implement a custom `errors.Is` method on `type ValidationErrors []FieldError` [as described in the docs](https://pkg.go.dev/errors@go1.17.1#Is)?

Would something like 

```go
func (ve *ValidationErrors) Is(target error) bool {
  validationErrors := err.(validator.ValidationErrors)
  if len(validationErrors) > 0 {
    return true
  }}
  return false
```

Sorry to raise the dead, @deankarn , just came across this issue. Lmk if I should add this and a handful of tests and I should be able to get a PR up near end of this week.

**Comment by deankarn** [comment]
@hampgoodwin thanks for the question.

Although it is possible to implement a custom Is function it would not be a correct usage. ￼Is function is used to check if an error in the chain matches, not to check i￼f an error is of a type.

Even if a custom Is function was implemented to return true, the errors in the strictest sense would NOT match because ValidationErrors is truly a dynamic value eg. ValidationErrors{} is not the same as ValidationErros{{...}} which is not the same as ValidationErrors{{...},{...}}

With dynamic Errors the As function should be used instead. I know it doesn't seem intuitive at first but you get used to using it in this manner. 

My rule of thumb is if you have to construct the target value when using the Is function, it's being used wrong and As should be preferred/used instead. (Yes there are exceptions to every rule, but very few and far between for this one)

I hope that helps clarify a little.

**Comment by hampgoodwin** [comment]
This does clarify. Sorry for such a delayed response. I'm finally figuring out GH notifications :D
Thanks a bunch!
