### ISSUE TITLE
字段类型为 uint时，len不生效

### ISSUE THREAD

**Issue by shang-yin** [go-playground/validator#605]
### Package version eg. v8, v9: 
v10

### Issue, Question or Enhancement:
我想验证手机验证码长度，我的验证码是长度为4的uint，我使用len=4验证，code为1231，总是提示我长度不对

### Code sample, to showcase or reproduce:

```go
type LoginWithCode struct {
	Mobile uint   `json:"mobile" binding:"required,len=11"`
	Code   uint `json:"code" binding:"required,len=4"`
}
```
错误消息：Code必须等于4

如果我将上面的代码修改为以下代码，验证就会通过
```go
type LoginWithCode struct {
	Mobile string `json:"mobile" binding:"required,numeric,len=11"`
	Code   string `json:"code" binding:"required,numeric,len=4"`
}
```

我看了文档，len是支持numbric的，但是我这边验证一直失败，请问是我哪里写错了吗？？？？

**Comment by deankarn** [comment]
Hey @shang-yin yes I see your issue, the `len` validation on numbers actually checks that the value is equal to 4 instead of the length. In hindsight this should check the length of the digits, however I'm worried about making a breaking change by fixing at this point.

I think it might be better served with a new validation maybe called `digits`, would you be able to help with a PR?

**Comment by shang-yin** [comment]
thanks
