### ISSUE TITLE
How can I use case insensitive values in oneof validator

### ISSUE THREAD

**Issue by vijsourabh** [go-playground/validator#840]
The case is I need to validate case insensitive oneof values in the field of JSON struct and not able to find anything. Can anyone suggest me anything to achieve the same?

**Comment by filikos** [comment]
The field to be compared with the `oneof` values can be converted to lower case before validating the struct.

**Comment by deankarn** [comment]
@vijsourabh as @filikos stated you could normalize the data if that's an option; here's a lib to help out with that https://github.com/go-playground/mold

If not then a custom validator is also an option.

**Comment by vijsourabh** [comment]
@deankarn & @filikos, It worked, Thanks :)

**Comment by draper-lucid** [comment]
This is a rather obtuse solution "downcase the value before validating" the point of the project is to add magic to model validation right? Adding another meta tag that will handle casing would be rather helpful. There are more applications to model validations that serving up 400s to a client, and using the same model across a platform is of benefit. I could accept "we are taking pull requests!" as a better answer than "downcase the value", it's essentially a non-answer.

**Comment by deankarn** [comment]
@draper-lucid

1. Please try not to comment on closed issues unless it's also asking to be re-opened.
2. `This is a rather obtuse solution` is it? Depends on your use case. Sanitization of data before storing is the norm in my experience ymmv. In any case, it's not a non-answer.
3. Nobody's stopping anyone from making a PR for a new validation tag, something like `case_insensitive_oneof` or alike.
4. Library also allows creating and registering custom validations for you use case that's not supported by default. In fact for `oneof` I usually register my own custom one in order to leverage an internal map, array etc.. that holds these concrete values in the code and if any are added or removed there's no forgetting to update the struct tags.

**Comment by mmengspv** [comment]
Just another idea

Register your new validation
```
validate.RegisterValidation("oneof_insensitive", validateOneOfInsensitive)
```

Validation logic for oneof_insensitive case
```
func validateOneOfInsensitive(fl validator.FieldLevel) bool {
	fieldValue := fl.Field().String()
	allowedValues := strings.Split(fl.Param(), " ")

	for _, allowedValue := range allowedValues {
		if strings.EqualFold(fieldValue, allowedValue) {
			return true
		}
	}

	return false
}
```
