### ISSUE TITLE
country_code alias panics on invalid iso3166_1_alpha2 and iso3166_1_alpha3

### ISSUE THREAD

**Issue by uberswe** [go-playground/validator#860]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Issue, Question or Enhancement:
In #615 the `country_code` alias is introduced which calls 3 validators `iso3166_1_alpha2|iso3166_1_alpha3|iso3166_1_alpha_numeric`. 

If you use the `country_code` to validate a string which has an invalid value you will receive a panic with the message `Bad field type string`. This is caused by the `iso3166_1_alpha_numeric` validation here https://github.com/go-playground/validator/blob/ce34f361cca51e25715399ab801c5e1c01d02d89/baked_in.go#L2359 .

### Code sample, to showcase or reproduce:

This is a test I wrote to confirm the issue, you will receive a panic on `"1"`.

```go
func TestCountryCodeValidation(t *testing.T) {
	tests := []struct {
		value    interface{}
		expected bool
	}{
		{248, true},
		{0, false},
		{1, false},
		{"NO", true},
		{"1", false},
		{"0", false},
	}

	validate := New()

	for i, test := range tests {

		errs := validate.Var(test.value, "country_code")

		if test.expected {
			if !IsEqual(errs, nil) {
				t.Fatalf("Index: %d country_code failed Error: %s", i, errs)
			}
		} else {
			if IsEqual(errs, nil) {
				t.Fatalf("Index: %d country_code failed Error: %s", i, errs)
			}
		}
	}
}
```

### Expected behaviour

I would expect that the alias should not panic here but instead return false.

### Fix

I was planning to make a PR for this issue but the fix may require some big changes and I thought it may be good to discuss them before making any kind of changes.

A simple solution would be to catch any panic for an alias, this makes sense for `country_code` which can have multiple valid types.

An easier solution would be to just remove the panic in the `iso3166_1_alpha_numeric` function but then it would differ from the rest of the package. That raises another question of whether the package should be throwing panics in the first place?

I am not sure what the best way to solve this would be and would look for input from maintainers or perhaps @krhubert who added this functionality.

**Comment by joekendal** [comment]
what a dreadful package this is

**Comment by deankarn** [comment]
Hey @uberswe 

It looks like when the country code validations were added support for `string` types wasn't added. I think all that needs to be done is to add a new case statement for string field data from a string to an int or uint and then do the same validation that exists today [here](https://github.com/go-playground/validator/blob/ce34f361cca51e25715399ab801c5e1c01d02d89/baked_in.go#L2354)

I'd rather keep the panic than returning false because `string` fields were NOT supported by this validation, returning false would give the indication it was working but...it's not.

It would be greatly appreciated if you could create a PR to add those other cases statements.

**Comment by deankarn** [comment]
@joekendal https://github.com/go-playground/validator/issues/860#issuecomment-1003481377

Your comment is extremely unhelpful and reflects poorly on yourself. I recommend reading [this](https://medium.com/@joeybloggs/online-etiquette-for-the-unenlightened-65245df548ff).

**Comment by joekendal** [comment]
> @joekendal https://github.com/go-playground/validator/issues/860#issuecomment-1003481377
> 
> 
> 
> Your comment is extremely unhelpful and reflects poorly on yourself. I recommend reading [this](https://medium.com/@joeybloggs/online-etiquette-for-the-unenlightened-65245df548ff).

Fine, sorry. But from my perspective I integrated this package because it looked popular and it turns out to be completely dysfunctional and poorly documented. The fact that this issue wasn't responded to either was the final nail in the coffin. If you're going to claim something is implemented you shouldn't throw a panic.

**Comment by uberswe** [comment]
Thank you for the feedback @deankarn, I agree with your suggestion and opened PR #873 which follows what you said.
