### ISSUE TITLE
Different behaviour depending on tag order when using dive with min/max/lte/gte

### ISSUE THREAD

**Issue by pgrubacc** [go-playground/validator#897]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Issue, Question or Enhancement:

Using the dive tag on a slice, along with tags like min/max/lte/gte, results in inconsistent behaviour. If the dive tag is at the beginning, it seems that the length is not checked at all. If the dive tag moved to the end of the tag list, then everything works as expected, the constraints are applied. 

I couldn't find anything in the documentation that would indicate the order of the tags is important in this case. Feel free to point me to the docs and close the issue if I've missed something, and thank you for working on this library. It's extremely convenient and easy to use.

Here's a [playground example](https://go.dev/play/p/OVnmGE1Xmol).

### Code sample, to showcase or reproduce:

```go
package main

import (
	"fmt"

	"github.com/go-playground/validator/v10"
)

type TestList struct {
	List []TestEl `json:"testEl" validate:"dive,required,min=1,max=3"`
}

type TestEl struct {
	Type string `json:"type" validate:"required"`
}

func main() {
	testList := TestList{
		List: []TestEl{
			{Type: "asd"},
			{Type: "asd2"},
			{Type: "asd3"},
			{Type: "asd4"},
		},
	}
	var validate *validator.Validate
	validate = validator.New()
	err := validate.Struct(testList)
	if err != nil {
		fmt.Println("Error occurred!") // not printed, if you put the dive tag last, we'll enter this code
	}
}
```

**Comment by zemzale** [comment]
Hey @pgrubacc. This is actually written in the docs right here: https://pkg.go.dev/github.com/go-playground/validator/v10#hdr-Dive

Specifically, this sentence explains it (the bold part is the important one):
> This tells the validator to dive into a slice, array or map and validate that level of the slice, array or map **with the validation tags that follow.**

So everything that **follows** the `dive` tag is not applied to the slice itself, but the elements inside the slice. In this case, because the elements inside are a struct, the `min`and `max` tags won't do anything, because they work only on numbers, strings, and maps/slices. 

I don't know what are you trying to do, but if you are trying to check if `Type` in `TypeEl` is set you don't have to use the `dive` here, because it will validate the tags on the `TypeEl` struct.

**Comment by pgrubacc** [comment]
Ah, I see. I was using `dive` because otherwise the validation of my nested struct's validate tags wasn't triggering, which is the expected behavior I believe. If I understood correctly, everything before the dive applies to the actual slice, whereas everything after the dive applies to the elements inside. Thanks for the clarification!
