### ISSUE TITLE
Confusion with regard to semantics of required for pointers

### ISSUE THREAD

**Issue by yourtallness** [go-playground/validator#932]
- [x] I have looked at the documentation [here](https://pkg.go.dev/github.com/go-playground/validator/v10#section-documentation) first?
- [x] I have looked at the examples provided that may showcase my question [here](/_examples)?

### Package version eg. v9, v10:

latest

### Issue, Question or Enhancement:

For validations that pertain to strings, like e.g. `min`, go validator dereferences the pointer and checks the value.

For `required` though, it seems it requires the pointer to be non-empty, even though the value might be equal to a zero value.

This allows e.g. a pointer to a zero value to be considered valid.

Is there a rule of thumb which validations are run on the pointer and which on the value?

### Code sample, to showcase or reproduce:

[go playground](https://go.dev/play/p/CoYM38aK-uY)

**Comment by zemzale** [comment]
The documentation is pretty clear on that IMO
> This validates that the value is not the data types default zero value. For numbers ensures value is not zero. For strings ensures value is not "". For slices, maps, pointers, interfaces, channels and functions ensures the value is not nil. 

The zero value for a pointer is `nil` so whatever the pointer is, it can't be nil and that is it. 

There might be a case for dereferencing built-in types e.g. string, int, and so on, but that is not something I think should be really considered, since you would use a pointer in most cases to differentiate between an empty string and null value, where the empty string has a different meaning than the null value.

**Comment by deankarn** [comment]
I will also add it’s an unfortunate quirk of Go whereby nil is a value in Go but design of the language and std library uses pointers to denote presence/empty, which make using nil as a valid value very hard.

**Comment by deankarn** [comment]
Closing as question was answered and no follow-up response.
